name: Tests
on: [pull_request]

jobs:
  test:
    environment: Development
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Generate auxiliary files
        run: make generate

      - name: Run tests
        run: make test